[project]
name = "artifacts-storage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.2.0",
    "pydantic>=2.9.2",
    "ruff>=0.12.2",
]
