[project]
name = "artifacts-storage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "plotly",
    "pydantic",
    "ruff",
]
